kind: CDN
version: '1'
metadata:
  envTypes:
    - dev
data:
  trafficFilters:
    rules:
      - name: publish-auth-requests
        when:
          allOf:
            - reqProperty: tier
              matches: publish
            - reqProperty: path
              in:
                - /system/sling/login/j_security_check
                - /system/sling/logout
        action: log
      - name: block-waf-flags
        when:
          reqProperty: path
          like: "*"
        action:
          type: block
          wafFlags: [SQLI, XSS, BACKDOOR, XML-ERROR, RESPONSESPLIT, SCANNER, PRIVATEFILE, NOUA, TORNODE, NULLBYTE, NO-CONTENT-TYPE, SANS, MALFORMED-DATA, JSON-ERROR, NOTUTF8, DOUBLEENCODING, ABNORMALPATH, CODEINJECTION, BHH, LOG4J-JNDI, USERAGENT, TRAVERSAL]
      - name: block-ofac-countries
        when:
          allOf:
            - reqProperty: tier
              matches: "author|publish"
            - reqProperty: clientCountry
              in:
                - SY
                - BY
                - MM
                - KP
                - IQ
                - CD
                - SD
                - IR
                - LR
                - ZW
                - CU
                - CI
        action: block
      - name: limit-requests-per-client-ip
        when:
          reqProperty: tier
          matches: "author|publish"
        rateLimit:
          limit: 100
          window: 1
          penalty: 300
          groupBy:
            - reqProperty: clientIp
        action: block